CREATE TABLE upload_link_sessions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    upload_link_id INTEGER NOT NULL REFERENCES upload_links(id) ON DELETE CASCADE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid BOOLEAN NOT NULL DEFAULT 1,
    session_token TEXT NOT NULL UNIQUE
)